# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "ahci" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    {
      device = "/dev/mapper/system";
      fsType = "btrfs";
      options = [ "subvol=nixos" ];
    };

  boot.initrd.luks.devices."system".device = "/dev/disk/by-uuid/ae5fc4cf-327b-4ee7-95fd-df23c1380fc9";

  fileSystems."/boot" =
    {
      device = "/dev/disk/by-uuid/D92C-E38A";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  fileSystems."/swap" =
    {
      device = "/dev/mapper/system";
      fsType = "btrfs";
      options = [ "subvol=swap" ];
    };

  fileSystems."/home" =
    {
      device = "/dev/mapper/system";
      fsType = "btrfs";
      options = [ "subvol=home" ];
    };

  fileSystems."/var/lib/docker" =
    { device = "/dev/mapper/system";
      fsType = "btrfs";
      options = [ "subvol=docker" ];
    };

  swapDevices = [{
    device = "/swap/swapfile";
    size = 20 * 1024;
  }];

  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  hardware.bluetooth = {
    enable = true;
    powerOnBoot = false;
    settings = {
      General = {
        Enable = "Source,Sink,Media,Socket";
        Experimental = true;
      };
    };
  };
}
