# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config
, lib
, pkgs
, modulesPath
, ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ahci"
    "nvme"
    "usb_storage"
    "usbhid"
    "sd_mod"
  ];
  hardware.cpu.intel.updateMicrocode = false;
  boot.kernelParams = [ "dis_ucode_ldr" ];
  boot.initrd.kernelModules = [ "i915" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];
  boot.supportedFilesystems = [ "ntfs" ];
  boot.tmp.cleanOnBoot = true;

  services.fstrim.enable = true;

  environment.variables = {
    VDPAU_DRIVER = "va_gl";
  };
  hardware.graphics.extraPackages = with pkgs; [
    (
      if (lib.versionOlder (lib.versions.majorMinor lib.version) "23.11") then
        vaapiIntel
      else
        intel-vaapi-driver
    )
    libvdpau-va-gl
    intel-media-driver
  ];

  # hardware.cpu.intel.sgx = true;

    fileSystems."/" =
    { device = "/dev/mapper/system";
      fsType = "btrfs";
      options = [ "subvol=nixosroot" ];
    };

  boot.initrd.luks.devices."system".device = "/dev/disk/by-uuid/958050bc-97b6-4757-b6f4-0b7507c9f5bc";

  fileSystems."/home" =
    { device = "/dev/mapper/system";
      fsType = "btrfs";
      options = [ "subvol=home" ];
    };

  fileSystems."/home/anas/code" =
    { device = "/dev/mapper/system";
      fsType = "btrfs";
      options = [ "subvol=code" ];
    };

  fileSystems."/home/anas/external-code" =
    { device = "/dev/mapper/system";
      fsType = "btrfs";
      options = [ "subvol=external-code" ];
    };

  fileSystems."/home/anas/.sec" =
    { device = "/dev/mapper/system";
      fsType = "btrfs";
      options = [ "subvol=sec" ];
    };

  fileSystems."/var/lib/docker" =
    { device = "/dev/mapper/system";
      fsType = "btrfs";
      options = [ "subvol=docker" ];
    };

  fileSystems."/swap" =
    { device = "/dev/mapper/system";
      fsType = "btrfs";
      options = [ "subvol=swap" ];
    };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/096E-C94D";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  fileSystems."/mnt/work" = {
    device = "/dev/disk/by-uuid/bee230d5-e78b-4abd-b3ec-699aa9426442";
    fsType = "ext4";
  };

  fileSystems."/mnt/data" = {
    device = "/dev/disk/by-uuid/01D7B7F51EFC4A00";
    fsType = "ntfs-3g";
    options = [ "rw" ];
  };

  fileSystems."/mnt/uni" = {
    device = "/dev/disk/by-uuid/01D74343567CAC80";
    fsType = "ntfs-3g";
    options = [ "rw" ];
  };

  swapDevices = [
    {
      device = "/swap/swapfile";
      size = 18 * 1024;
    }
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp7s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp0s20f3.useDHCP = lib.mkDefault true;

  # hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  # TLP
  services.tlp = {
    enable = true;
    settings = {
      # Select a CPU frequency scaling governor.
      # Intel processor with intel_pstate driver:
      #   performance, powersave(*).
      # Intel processor with intel_cpufreq driver (aka intel_pstate passive mode):
      #   conservative, ondemand, userspace, powersave, performance, schedutil(*).
      # Intel and other processor brands with acpi-cpufreq driver:
      #   conservative, ondemand(*), userspace, powersave, performance, schedutil(*).
      # Use tlp-stat -p to show the active driver and available governors.
      # Important:
      #   Governors marked (*) above are power efficient for *almost all* workloads
      #   and therefore kernel and most distributions have chosen them as defaults.
      #   You should have done your research about advantages/disadvantages *before*
      #   changing the governor.
      CPU_SCALING_GOVERNOR_ON_AC = "powersave";
      CPU_SCALING_GOVERNOR_ON_BAT = "powersave";

      CPU_ENERGY_PERF_POLICY_ON_AC = "balance_performance";
      CPU_ENERGY_PERF_POLICY_ON_BAT = "power";

      PLATFORM_PROFILE_ON_AC = "performance";
      PLATFORM_PROFILE_ON_BAT = "low-power";

      # Prevent USB autosuspend from stuttering/dropping bluetooth audio
      USB_AUTOSUSPEND = 0;

      CPU_HWP_DYN_BOOST_ON_AC = 1;
      CPU_HWP_DYN_BOOST_ON_BAT = 0;

      CPU_MIN_PERF_ON_AC = 0;
      CPU_MAX_PERF_ON_AC = 100;
      CPU_MIN_PERF_ON_BAT = 0;
      CPU_MAX_PERF_ON_BAT = 90;

      #Optional helps save long term battery health
      START_CHARGE_THRESH_BAT0 = 40; # 40 and below it starts to charge
      STOP_CHARGE_THRESH_BAT0 = 1;
      RESTORE_THRESHOLDS_ON_BAT = 1;
    };
  };

  # Thermald proactively prevents overheating on Intel CPUs and works well with other tools.
  services.thermald.enable = true;
  powerManagement.enable = true;

  hardware.bluetooth = {
    enable = true;
    powerOnBoot = true;
    settings = {
      General = {
        Enable = "Source,Sink,Media,Socket";
        Experimental = true; # WirePlumber supports the experimental LE audio (BAP) path
      };
    };
  };

}
